# Generated by Django 3.1.5 on 2021-06-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0008_remove_user_contact1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendeur',
            name='contact1',
        ),
        migrations.AlterField(
            model_name='vendeur',
            name='produits_vendu',
            field=models.TextField(blank=True, null=True),
        ),
    ]
