# Generated by Django 3.1.5 on 2021-06-28 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0009_auto_20210627_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Client.user'),
        ),
    ]
