# Generated by Django 3.1.5 on 2021-06-28 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0010_auto_20210628_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EnvieProduit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.envie')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.produit')),
            ],
        ),
        migrations.AddField(
            model_name='envie',
            name='produit',
            field=models.ManyToManyField(through='Client.EnvieProduit', to='Client.Produit'),
        ),
        migrations.AddField(
            model_name='envie',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Client.user'),
        ),
    ]
